version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - '5432'

  adminpanel:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - '8080:8080'

  chatbot:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - '8081:8080'
