version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_ROOT_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_TCP_PORT=${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}

  api:
    container_name: api
    image: spring-boot-api
    build: api/.
    env_file: ./.env
    ports:
      - ${API_PORT}:${API_PORT}
      - "5005:5005"
    depends_on:
      - postgres
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
      - spring.datasource.username=${DB_USER}
      - spring.datasource.password=${DB_PASSWORD}
      - spring.jpa.hibernate.ddl-auto=validate

  frontend:
    container_name: frontend
    image: frontend
    build: frontend/.
    ports:
      - "4200:4200"
    depends_on:
      - api